name: Release on tag

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 16
        uses: actions/setup-node@master
        with:
          version: 16
          cache: npm
      - name: Get package version
        id: ref
        run: |
          pkgver=$(node ./scripts/version.js)
          echo ::set-output name=version::$pkgver
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Create a release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ steps.ref.outputs.version }}
          tag_name: ${{ steps.ref.outputs.version }}
          files: |
            ./release/${{steps.ref.outputs.version}}/based-launcher-Linux-${{steps.ref.outputs.version}}.deb
            ./release/${{steps.ref.outputs.version}}/based-launcher-Linux-${{steps.ref.outputs.version}}.AppImage
            ./release/${{steps.ref.outputs.version}}/based-launcher-Linux-${{steps.ref.outputs.version}}.pacman
            ./release/${{steps.ref.outputs.version}}/based-launcher-Linux-${{steps.ref.outputs.version}}.tar.gz